### PR TITLE
Fix custom field names

### PR DESCRIPTION
**Pull request by crowemi**
**Are you a current Fivetran customer?** 
crowemi, Data Engineer, Subsplash

**What change(s) does this PR introduce?** 
Created `set_safe_col_name` macro which checks that that the `issue_field_history_columns` contain safe column name for the database engine (e.g. remove leading numeric character from column name)

**Did you update the CHANGELOG?** 
- [x] Yes

**Does this PR introduce a breaking change?**
- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] Yes, Issue/Feature [71](https://github.com/fivetran/dbt_jira/issues/71)
- [ ] No 

**How did you test the PR changes?** 
- [ ] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
🌲 

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

### CODE REVIEW

**Comment by crowemi** [comment]
@fivetran-joemarkiewicz -- let me know if you want me to add that flag, etc. 🤷‍♂️

**Comment by fivetran-joemarkiewicz** [comment]
Thanks so much for opening this @crowemi!

Just to give you an ETA, we probably won't get to this until the week of 10/24 as we will be attending the Coalesce conference! I apologize for the long wait, but we will be sure to let you know if we have any feedback once we jump back in!

**Comment by crowemi** [comment]
No worries and no rush on my end. I moved forward with my changes internally when I initially reported. I intend on switching back once we get it merged and deployed. Have fun at Coalesce!!

**Comment by crowemi** [comment]
this issue was fixed here: [#76](https://github.com/fivetran/dbt_jira/pull/76)

**Pull request closed without merging**
